openapi: 3.2.0
info:
  title: ComboCurve REST Ownership Reversion API
  version: 1.0.0
servers:
- url: https://api.combocurve.com
security:
- api-key: []
  service-account-key: []
tags:
- name: OwnershipReversion
paths:
  /v1/projects/{projectId}/econ-models/ownership-reversions:
    head:
      description: Returns metadata about the existing ownership reversions documents.
      operationId: head-ownership-reversions
      parameters:
      - $ref: '#/components/parameters/skipParam'
      - $ref: '#/components/parameters/takeParam'
      - in: path
        name: projectId
        required: true
        schema:
          type: string
      - name: createdAt
        in: query
        description: filter by createdAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example createdAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      - name: name
        in: query
        description: filter by name
        schema:
          type: string
      - name: well
        in: query
        description: filter by well
        schema:
          type: string
      - name: unique
        in: query
        description: filter by unique
        schema:
          type: boolean
      - name: updatedAt
        in: query
        description: filter by updatedAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example updatedAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: OK
          headers:
            Link:
              description: Indicates a typed relationship with another resource, where the relation type is defined by RFC 5988. We include the relationships next, prev, first and last, which can be used to move between pages of the list of results.
              schema:
                type: string
            X-Query-Count:
              description: The number of records in this resource. When filters are provided only matching records are counted.
              schema:
                type: integer
        '400':
          description: Bad Request. There is something wrong with the request data.
      tags:
      - OwnershipReversion
      summary: Head ownership reversions
      x-summary-source: derived
    get:
      description: Returns a list of ownership reversions documents.
      operationId: get-ownership-reversions
      parameters:
      - $ref: '#/components/parameters/skipParam'
      - $ref: '#/components/parameters/takeParam'
      - $ref: '#/components/parameters/sortParam'
      - $ref: '#/components/parameters/cursorParam'
      - in: path
        name: projectId
        required: true
        schema:
          type: string
      - name: createdAt
        in: query
        description: filter by createdAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example createdAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      - name: name
        in: query
        description: filter by name
        schema:
          type: string
      - name: well
        in: query
        description: filter by well
        schema:
          type: string
      - name: unique
        in: query
        description: filter by unique
        schema:
          type: boolean
      - name: updatedAt
        in: query
        description: filter by updatedAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example updatedAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: OK
          headers:
            Link:
              description: Indicates a typed relationship with another resource, where the relation type is defined by RFC 5988. We include the relationships next, prev, first and last, which can be used to move between pages of the list of results.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnershipReversionList'
              example:
              - id: 5e272d39b78910dd2a1bd8fe
                copiedFrom: 63b856e816f758cc5b0f1106
                name: Test
                scenario: 63b8571d70ed63f50bd6d63f
                tags:
                - 63b85737ff846cee7b1f6fdc
                unique: true
                well: 63b85759e1d7eb4e31579f51
                createdAt: '2020-01-21T16:58:08.986Z'
                updatedAt: '2020-01-21T17:58:08.986Z'
                createdBy: 63b857cb68f3b96efc700998
                lastUpdatedBy: 63b857cb68f3b96efc700998
                ownership: null
                initialOwnership:
                  workingInterest: 100
                  netProfitInterestType: expense
                  netProfitInterest: 0
                  netRevenueInterest: 100
                  leaseNetRevenueInterest: 75
                  oilNetRevenueInterest: 4
                  gasNetRevenueInterest: null
                  nglNetRevenueInterest: null
                  dripCondensateNetRevenueInterest: null
                firstReversion:
                  reversionType: Irr
                  reversionValue: 2
                  balance: gross
                  includeNetProfitInterest: 'yes'
                  workingInterest: 100
                  netProfitInterest: 0
                  netRevenueInterest: 100
                  leaseNetRevenueInterest: 75
                  oilNetRevenueInterest: null
                  gasNetRevenueInterest: null
                  nglNetRevenueInterest: null
                  dripCondensateNetRevenueInterest: null
                secondReversion:
                  reversionType: PayoutWithoutInvestment
                  reversionValue: 4
                  balance: gross
                  includeNetProfitInterest: 'yes'
                  workingInterest: 100
                  netProfitInterest: 0
                  netRevenueInterest: 100
                  leaseNetRevenueInterest: 75
                  oilNetRevenueInterest: 1
                  gasNetRevenueInterest: null
                  nglNetRevenueInterest: null
                  dripCondensateNetRevenueInterest: null
                thirdReversion:
                  reversionType: UndiscRoi
                  reversionValue: 3
                  balance: gross
                  includeNetProfitInterest: 'yes'
                  workingInterest: 100
                  netProfitInterest: 0
                  netRevenueInterest: 100
                  leaseNetRevenueInterest: 75
                  oilNetRevenueInterest: null
                  gasNetRevenueInterest: null
                  nglNetRevenueInterest: null
                  dripCondensateNetRevenueInterest: null
                fourthReversion: null
                fifthReversion: null
                sixthReversion: null
                seventhReversion: null
                eighthReversion: null
                ninthReversion: null
                tenthReversion: null
        '400':
          description: Bad Request. There is something wrong with the request data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                name: ValidationError
                message: The field 'id' is required.
                details:
                  location: In body of request at position [0]
      tags:
      - OwnershipReversion
      x-google-quota:
        metricCosts:
          read-request-rate: 1
      summary: Get ownership reversions
      x-summary-source: derived
    post:
      description: Inserts a list of ownership reversions documents.
      operationId: post-ownership-reversions
      parameters:
      - in: path
        name: projectId
        required: true
        schema:
          type: string
      responses:
        '207':
          description: Multi-Status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnershipReversionMultiStatusResponse'
              example:
                generalErrors:
                - name: ValidationError
                  message: The field 'name' is required.
                  location: In body of request at position [0]
                - name: ValidationError
                  message: The field 'unique' is required.
                  location: In body of request at position [2]
                results:
                - status: Success
                  code: 200
                  name: test
                - status: Success
                  code: 200
                  name: test1
                failedCount: 2
                successCount: 2
      tags:
      - OwnershipReversion
      x-google-quota:
        metricCosts:
          write-request-rate: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OwnershipReversionInputList'
        description: Ownership Reversions document(s) to insert. See OwnershipReversionInputList.
      summary: Post ownership reversions
      x-summary-source: derived
    put:
      description: Replace or create a list of ownership reversions documents.
      operationId: put-ownership-reversions
      parameters:
      - in: path
        name: projectId
        required: true
        schema:
          type: string
      responses:
        '207':
          description: Multi-Status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnershipReversionMultiStatusResponse'
              example:
                generalErrors:
                - name: ValidationError
                  message: The field 'name' is required.
                  location: In body of request at position [0]
                - name: ValidationError
                  message: The field 'unique' is required.
                  location: In body of request at position [2]
                results:
                - status: Success
                  code: 200
                  name: test
                - status: Success
                  code: 200
                  name: test1
                failedCount: 2
                successCount: 2
      tags:
      - OwnershipReversion
      x-google-quota:
        metricCosts:
          write-request-rate: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OwnershipReversionInputList'
        description: Ownership Reversions document(s) to replace/create. See OwnershipReversionInputList.
      summary: Put ownership reversions
      x-summary-source: derived
  /v1/projects/{projectId}/econ-models/ownership-reversions/{id}:
    get:
      description: Returns the Ownership Reversions document that matches the given id.
      operationId: get-ownership-reversion-by-id
      parameters:
      - in: path
        name: projectId
        required: true
        schema:
          type: string
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnershipReversion'
              example:
                id: 5e272d39b78910dd2a1bd8fe
                copiedFrom: 63b856e816f758cc5b0f1106
                name: Test
                scenario: 63b8571d70ed63f50bd6d63f
                tags:
                - 63b85737ff846cee7b1f6fdc
                unique: true
                well: 63b85759e1d7eb4e31579f51
                createdAt: '2020-01-21T16:58:08.986Z'
                updatedAt: '2020-01-21T17:58:08.986Z'
                createdBy: 63b857cb68f3b96efc700998
                lastUpdatedBy: 63b857cb68f3b96efc700998
                ownership:
                  initialOwnership:
                    workingInterest: 100
                    netProfitInterestType: expense
                    netProfitInterest: 0
                    netRevenueInterest: 100
                    leaseNetRevenueInterest: 75
                    oilNetRevenueInterest: 4
                    gasNetRevenueInterest: null
                    nglNetRevenueInterest: null
                    dripCondensateNetRevenueInterest: null
                  firstReversion:
                    reversionType: Irr
                    reversionValue: 2
                    balance: gross
                    includeNetProfitInterest: 'yes'
                    workingInterest: 100
                    netProfitInterest: 0
                    netRevenueInterest: 100
                    leaseNetRevenueInterest: 75
                    oilNetRevenueInterest: null
                    gasNetRevenueInterest: null
                    nglNetRevenueInterest: null
                    dripCondensateNetRevenueInterest: null
                  secondReversion:
                    reversionType: PayoutWithoutInvestment
                    reversionValue: 4
                    balance: gross
                    includeNetProfitInterest: 'yes'
                    workingInterest: 100
                    netProfitInterest: 0
                    netRevenueInterest: 100
                    leaseNetRevenueInterest: 75
                    oilNetRevenueInterest: 1
                    gasNetRevenueInterest: null
                    nglNetRevenueInterest: null
                    dripCondensateNetRevenueInterest: null
                  thirdReversion:
                    reversionType: UndiscRoi
                    reversionValue: 3
                    balance: gross
                    includeNetProfitInterest: 'yes'
                    workingInterest: 100
                    netProfitInterest: 0
                    netRevenueInterest: 100
                    leaseNetRevenueInterest: 75
                    oilNetRevenueInterest: null
                    gasNetRevenueInterest: null
                    nglNetRevenueInterest: null
                    dripCondensateNetRevenueInterest: null
                  fourthReversion: null
                  fifthReversion: null
                  sixthReversion: null
                  seventhReversion: null
                  eighthReversion: null
                  ninthReversion: null
                  tenthReversion: null
        '400':
          description: Bad Request. There is something wrong with the request data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                name: ValidationError
                message: The field 'id' is required.
                details:
                  location: In body of request at position [0]
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                name: ValidationError
                message: The field 'id' is required.
                details:
                  location: In body of request at position [0]
      tags:
      - OwnershipReversion
      x-google-quota:
        metricCosts:
          read-request-rate: 1
      summary: Get ownership reversion by id
      x-summary-source: derived
    delete:
      description: Delete the assumptions document that matches the given id scoped to projectId project.
      operationId: delete-ownership-reversion-by-id
      parameters:
      - in: path
        name: projectId
        required: true
        description: ''
        schema:
          type: string
      - in: path
        name: id
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: OK
          headers:
            X-Delete-Count:
              description: The number of records that match the given filters and were deleted.
              schema:
                type: integer
        '400':
          description: Bad Request. There is something wrong with the request data.
      tags:
      - OwnershipReversion
      summary: Delete ownership reversion by id
      x-summary-source: derived
  /v1/econ-models/ownership-reversions:
    head:
      description: Returns metadata about the existing ownership reversions documents.
      operationId: head-company-ownership-reversions
      parameters:
      - $ref: '#/components/parameters/skipParam'
      - $ref: '#/components/parameters/takeParam'
      - name: createdAt
        in: query
        description: filter by createdAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example createdAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      - name: name
        in: query
        description: filter by name
        schema:
          type: string
      - name: well
        in: query
        description: filter by well
        schema:
          type: string
      - name: unique
        in: query
        description: filter by unique
        schema:
          type: boolean
      - name: updatedAt
        in: query
        description: filter by updatedAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example updatedAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: OK
          headers:
            Link:
              description: Indicates a typed relationship with another resource, where the relation type is defined by RFC 5988. We include the relationships next, prev, first and last, which can be used to move between pages of the list of results.
              schema:
                type: string
            X-Query-Count:
              description: The number of records in this resource. When filters are provided only matching records are counted.
              schema:
                type: integer
        '400':
          description: Bad Request. There is something wrong with the request data.
      tags:
      - OwnershipReversion
      summary: Head company ownership reversions
      x-summary-source: derived
    get:
      description: Returns a list of ownership reversions documents.
      operationId: get-company-ownership-reversions
      parameters:
      - $ref: '#/components/parameters/skipParam'
      - $ref: '#/components/parameters/takeParam'
      - $ref: '#/components/parameters/sortParam'
      - $ref: '#/components/parameters/cursorParam'
      - name: createdAt
        in: query
        description: filter by createdAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example createdAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      - name: name
        in: query
        description: filter by name
        schema:
          type: string
      - name: well
        in: query
        description: filter by well
        schema:
          type: string
      - name: unique
        in: query
        description: filter by unique
        schema:
          type: boolean
      - name: updatedAt
        in: query
        description: filter by updatedAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example updatedAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: OK
          headers:
            Link:
              description: Indicates a typed relationship with another resource, where the relation type is defined by RFC 5988. We include the relationships next, prev, first and last, which can be used to move between pages of the list of results.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnershipReversionList'
              example:
              - id: 5e272d39b78910dd2a1bd8fe
                copiedFrom: 63b856e816f758cc5b0f1106
                name: Test
                scenario: 63b8571d70ed63f50bd6d63f
                tags:
                - 63b85737ff846cee7b1f6fdc
                unique: true
                well: 63b85759e1d7eb4e31579f51
                createdAt: '2020-01-21T16:58:08.986Z'
                updatedAt: '2020-01-21T17:58:08.986Z'
                createdBy: 63b857cb68f3b96efc700998
                lastUpdatedBy: 63b857cb68f3b96efc700998
                ownership: null
                initialOwnership:
                  workingInterest: 100
                  netProfitInterestType: expense
                  netProfitInterest: 0
                  netRevenueInterest: 100
                  leaseNetRevenueInterest: 75
                  oilNetRevenueInterest: 4
                  gasNetRevenueInterest: null
                  nglNetRevenueInterest: null
                  dripCondensateNetRevenueInterest: null
                firstReversion:
                  reversionType: Irr
                  reversionValue: 2
                  balance: gross
                  includeNetProfitInterest: 'yes'
                  workingInterest: 100
                  netProfitInterest: 0
                  netRevenueInterest: 100
                  leaseNetRevenueInterest: 75
                  oilNetRevenueInterest: null
                  gasNetRevenueInterest: null
                  nglNetRevenueInterest: null
                  dripCondensateNetRevenueInterest: null
                secondReversion:
                  reversionType: PayoutWithoutInvestment
                  reversionValue: 4
                  balance: gross
                  includeNetProfitInterest: 'yes'
                  workingInterest: 100
                  netProfitInterest: 0
                  netRevenueInterest: 100
                  leaseNetRevenueInterest: 75
                  oilNetRevenueInterest: 1
                  gasNetRevenueInterest: null
                  nglNetRevenueInterest: null
                  dripCondensateNetRevenueInterest: null
                thirdReversion:
                  reversionType: UndiscRoi
                  reversionValue: 3
                  balance: gross
                  includeNetProfitInterest: 'yes'
                  workingInterest: 100
                  netProfitInterest: 0
                  netRevenueInterest: 100
                  leaseNetRevenueInterest: 75
                  oilNetRevenueInterest: null
                  gasNetRevenueInterest: null
                  nglNetRevenueInterest: null
                  dripCondensateNetRevenueInterest: null
                fourthReversion: null
                fifthReversion: null
                sixthReversion: null
                seventhReversion: null
                eighthReversion: null
                ninthReversion: null
                tenthReversion: null
        '400':
          description: Bad Request. There is something wrong with the request data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                name: ValidationError
                message: The field 'id' is required.
                details:
                  location: In body of request at position [0]
      tags:
      - OwnershipReversion
      x-google-quota:
        metricCosts:
          read-request-rate: 1
      summary: Get company ownership reversions
      x-summary-source: derived
    post:
      description: Inserts a list of ownership reversions documents.
      operationId: post-company-ownership-reversions
      responses:
        '207':
          description: Multi-Status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnershipReversionMultiStatusResponse'
              example:
                generalErrors:
                - name: ValidationError
                  message: The field 'name' is required.
                  location: In body of request at position [0]
                - name: ValidationError
                  message: The field 'unique' is required.
                  location: In body of request at position [2]
                results:
                - status: Success
                  code: 200
                  name: test
                - status: Success
                  code: 200
                  name: test1
                failedCount: 2
                successCount: 2
      tags:
      - OwnershipReversion
      x-google-quota:
        metricCosts:
          write-request-rate: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OwnershipReversionInputList'
        description: Ownership Reversions document(s) to insert. See OwnershipReversionInputList.
      summary: Post company ownership reversions
      x-summary-source: derived
    put:
      description: Replace or create a list of ownership reversions documents.
      operationId: put-company-ownership-reversions
      responses:
        '207':
          description: Multi-Status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnershipReversionMultiStatusResponse'
              example:
                generalErrors:
                - name: ValidationError
                  message: The field 'name' is required.
                  location: In body of request at position [0]
                - name: ValidationError
                  message: The field 'unique' is required.
                  location: In body of request at position [2]
                results:
                - status: Success
                  code: 200
                  name: test
                - status: Success
                  code: 200
                  name: test1
                failedCount: 2
                successCount: 2
      tags:
      - OwnershipReversion
      x-google-quota:
        metricCosts:
          write-request-rate: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OwnershipReversionInputList'
        description: Ownership Reversions document(s) to replace/create. See OwnershipReversionInputList.
      summary: Put company ownership reversions
      x-summary-source: derived
  /v1/econ-models/ownership-reversions/{id}:
    get:
      description: Returns the Ownership Reversions document that matches the given id.
      operationId: get-company-ownership-reversion-by-id
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnershipReversion'
              example:
                id: 5e272d39b78910dd2a1bd8fe
                copiedFrom: 63b856e816f758cc5b0f1106
                name: Test
                scenario: 63b8571d70ed63f50bd6d63f
                tags:
                - 63b85737ff846cee7b1f6fdc
                unique: true
                well: 63b85759e1d7eb4e31579f51
                createdAt: '2020-01-21T16:58:08.986Z'
                updatedAt: '2020-01-21T17:58:08.986Z'
                createdBy: 63b857cb68f3b96efc700998
                lastUpdatedBy: 63b857cb68f3b96efc700998
                ownership:
                  initialOwnership:
                    workingInterest: 100
                    netProfitInterestType: expense
                    netProfitInterest: 0
                    netRevenueInterest: 100
                    leaseNetRevenueInterest: 75
                    oilNetRevenueInterest: 4
                    gasNetRevenueInterest: null
                    nglNetRevenueInterest: null
                    dripCondensateNetRevenueInterest: null
                  firstReversion:
                    reversionType: Irr
                    reversionValue: 2
                    balance: gross
                    includeNetProfitInterest: 'yes'
                    workingInterest: 100
                    netProfitInterest: 0
                    netRevenueInterest: 100
                    leaseNetRevenueInterest: 75
                    oilNetRevenueInterest: null
                    gasNetRevenueInterest: null
                    nglNetRevenueInterest: null
                    dripCondensateNetRevenueInterest: null
                  secondReversion:
                    reversionType: PayoutWithoutInvestment
                    reversionValue: 4
                    balance: gross
                    includeNetProfitInterest: 'yes'
                    workingInterest: 100
                    netProfitInterest: 0
                    netRevenueInterest: 100
                    leaseNetRevenueInterest: 75
                    oilNetRevenueInterest: 1
                    gasNetRevenueInterest: null
                    nglNetRevenueInterest: null
                    dripCondensateNetRevenueInterest: null
                  thirdReversion:
                    reversionType: UndiscRoi
                    reversionValue: 3
                    balance: gross
                    includeNetProfitInterest: 'yes'
                    workingInterest: 100
                    netProfitInterest: 0
                    netRevenueInterest: 100
                    leaseNetRevenueInterest: 75
                    oilNetRevenueInterest: null
                    gasNetRevenueInterest: null
                    nglNetRevenueInterest: null
                    dripCondensateNetRevenueInterest: null
                  fourthReversion: null
                  fifthReversion: null
                  sixthReversion: null
                  seventhReversion: null
                  eighthReversion: null
                  ninthReversion: null
                  tenthReversion: null
        '400':
          description: Bad Request. There is something wrong with the request data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                name: ValidationError
                message: The field 'id' is required.
                details:
                  location: In body of request at position [0]
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                name: ValidationError
                message: The field 'id' is required.
                details:
                  location: In body of request at position [0]
      tags:
      - OwnershipReversion
      x-google-quota:
        metricCosts:
          read-request-rate: 1
      summary: Get company ownership reversion by id
      x-summary-source: derived
    delete:
      description: Delete the assumptions document that matches the given id scoped to company level
      operationId: delete-company-ownership-reversion-by-id
      parameters:
      - in: path
        name: id
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: OK
          headers:
            X-Delete-Count:
              description: The number of records that match the given filters and were deleted.
              schema:
                type: integer
        '400':
          description: Bad Request. There is something wrong with the request data.
      tags:
      - OwnershipReversion
      summary: Delete company ownership reversion by id
      x-summary-source: derived
components:
  schemas:
    Error:
      type: object
      properties:
        name:
          type: string
          description: The kind of error.
        message:
          type: string
          description: A human-readable description of the problem.
        details:
          type: object
          properties:
            location:
              type: string
              description: The location in the request data that contains the invalid value.
      example:
        name: ValidationError
        message: The field 'id' is required.
        details:
          location: In body of request at position [0]
    OwnershipReversionStatus:
      type: object
      required:
      - status
      - code
      properties:
        status:
          type: string
        code:
          type: integer
        name:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorEntry'
      example:
        status: Success
        code: 200
        name: test
    OwnershipReversionMultiStatusResponse:
      type: object
      properties:
        generalErrors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorEntry'
        results:
          type: array
          items:
            $ref: '#/components/schemas/OwnershipReversionStatus'
        failedCount:
          type: integer
        successCount:
          type: integer
      example:
        generalErrors:
        - name: ValidationError
          message: The field 'name' is required.
          location: In body of request at position [0]
        - name: ValidationError
          message: The field 'unique' is required.
          location: In body of request at position [2]
        results:
        - status: Success
          code: 200
          name: test
        - status: Success
          code: 200
          name: test1
        failedCount: 2
        successCount: 2
    OwnershipReversion:
      type: object
      required:
      - name
      - unique
      properties:
        name:
          type: string
          description: Name
        unique:
          type: boolean
          description: Unique
        id:
          type: string
          description: ID
        copiedFrom:
          type: string
          description: Copied From
        scenario:
          type: string
          description: Scenario ID
        tags:
          type: array
          items:
            type: string
            description: Tag ID
        well:
          type: string
          description: Well ID
        createdAt:
          type: string
          format: date
          description: Creation Date
        updatedAt:
          type: string
          format: date
          description: Updated At
        createdBy:
          type: string
          description: Created By
        lastUpdatedBy:
          type: string
          description: Last Updated By
        ownership:
          type: object
          properties:
            initialOwnership:
              type: object
              properties:
                workingInterest:
                  type: number
                  description: working Interest
                netProfitInterestType:
                  type: string
                  description: Net Profit Interest Type
                netProfitInterest:
                  type: number
                  description: Net Profit Interest
                netRevenueInterest:
                  type: number
                  description: Net Revenue Interest
                leaseNetRevenueInterest:
                  type: number
                  description: Lease Net Revenue Interest
                oilNetRevenueInterest:
                  type: number
                  description: Oil Net Revenue Interest
                gasNetRevenueInterest:
                  type: number
                  description: Gas Net Revenue Interest
                nglNetRevenueInterest:
                  type: number
                  description: Ngl Net Revenue Interest
                dripCondensateNetRevenueInterest:
                  type: number
                  description: Drip Condensate Net Revenue Interest
            firstReversion:
              $ref: '#/components/schemas/Reversion'
            secondReversion:
              $ref: '#/components/schemas/Reversion'
            thirdReversion:
              $ref: '#/components/schemas/Reversion'
            fourthReversion:
              $ref: '#/components/schemas/Reversion'
            fifthReversion:
              $ref: '#/components/schemas/Reversion'
            sixthReversion:
              $ref: '#/components/schemas/Reversion'
            seventhReversion:
              $ref: '#/components/schemas/Reversion'
            eighthReversion:
              $ref: '#/components/schemas/Reversion'
            ninthReversion:
              $ref: '#/components/schemas/Reversion'
            tenthReversion:
              $ref: '#/components/schemas/Reversion'
      example:
        id: 5e272d39b78910dd2a1bd8fe
        copiedFrom: 63b856e816f758cc5b0f1106
        name: Test
        scenario: 63b8571d70ed63f50bd6d63f
        tags:
        - 63b85737ff846cee7b1f6fdc
        unique: true
        well: 63b85759e1d7eb4e31579f51
        createdAt: '2020-01-21T16:58:08.986Z'
        updatedAt: '2020-01-21T17:58:08.986Z'
        createdBy: 63b857cb68f3b96efc700998
        lastUpdatedBy: 63b857cb68f3b96efc700998
        ownership:
          initialOwnership:
            workingInterest: 100
            netProfitInterestType: expense
            netProfitInterest: 0
            netRevenueInterest: 100
            leaseNetRevenueInterest: 75
            oilNetRevenueInterest: 4
            gasNetRevenueInterest: null
            nglNetRevenueInterest: null
            dripCondensateNetRevenueInterest: null
          firstReversion:
            reversionType: Irr
            reversionValue: 2
            balance: gross
            includeNetProfitInterest: 'yes'
            workingInterest: 100
            netProfitInterest: 0
            netRevenueInterest: 100
            leaseNetRevenueInterest: 75
            oilNetRevenueInterest: null
            gasNetRevenueInterest: null
            nglNetRevenueInterest: null
            dripCondensateNetRevenueInterest: null
          secondReversion:
            reversionType: PayoutWithoutInvestment
            reversionValue: 4
            balance: gross
            includeNetProfitInterest: 'yes'
            workingInterest: 100
            netProfitInterest: 0
            netRevenueInterest: 100
            leaseNetRevenueInterest: 75
            oilNetRevenueInterest: 1
            gasNetRevenueInterest: null
            nglNetRevenueInterest: null
            dripCondensateNetRevenueInterest: null
          thirdReversion:
            reversionType: UndiscRoi
            reversionValue: 3
            balance: gross
            includeNetProfitInterest: 'yes'
            workingInterest: 100
            netProfitInterest: 0
            netRevenueInterest: 100
            leaseNetRevenueInterest: 75
            oilNetRevenueInterest: null
            gasNetRevenueInterest: null
            nglNetRevenueInterest: null
            dripCondensateNetRevenueInterest: null
          fourthReversion: null
          fifthReversion: null
          sixthReversion: null
          seventhReversion: null
          eighthReversion: null
          ninthReversion: null
          tenthReversion: null
    ErrorEntry:
      required:
      - name
      - message
      type: object
      properties:
        name:
          type: string
        message:
          type: string
        location:
          type: string
      example:
        name: ValidationError
        message: The field 'id' is required.
        location: In body of request at position [0]
    Reversion:
      type: object
      discriminator:
        propertyName: reversionType
      required:
      - reversionType
      properties:
        reversionType:
          type: string
          description: Reversion Type
        balance:
          type: string
          description: Balance
        includeNetProfitInterest:
          type: string
          description: Include Net Profit Interest
        workingInterest:
          type: number
          description: working Interest
        netProfitInterest:
          type: number
          description: Net Profit Interest
        netRevenueInterest:
          type: number
          description: Net Revenue Interest
        leaseNetRevenueInterest:
          type: number
          description: Lease Net Revenue Interest
        oilNetRevenueInterest:
          type: number
          description: Oil Net Revenue Interest
        gasNetRevenueInterest:
          type: number
          description: Gas Net Revenue Interest
        nglNetRevenueInterest:
          type: number
          description: Ngl Net Revenue Interest
        dripCondensateNetRevenueInterest:
          type: number
          description: Drip Condensate Net Revenue Interest
    OwnershipReversionList:
      type: array
      items:
        $ref: '#/components/schemas/OwnershipReversion'
      maxItems: 200
      example:
      - id: 5e272d39b78910dd2a1bd8fe
        copiedFrom: 63b856e816f758cc5b0f1106
        name: Test
        scenario: 63b8571d70ed63f50bd6d63f
        tags:
        - 63b85737ff846cee7b1f6fdc
        unique: true
        well: 63b85759e1d7eb4e31579f51
        createdAt: '2020-01-21T16:58:08.986Z'
        updatedAt: '2020-01-21T17:58:08.986Z'
        createdBy: 63b857cb68f3b96efc700998
        lastUpdatedBy: 63b857cb68f3b96efc700998
        ownership: null
        initialOwnership:
          workingInterest: 100
          netProfitInterestType: expense
          netProfitInterest: 0
          netRevenueInterest: 100
          leaseNetRevenueInterest: 75
          oilNetRevenueInterest: 4
          gasNetRevenueInterest: null
          nglNetRevenueInterest: null
          dripCondensateNetRevenueInterest: null
        firstReversion:
          reversionType: Irr
          reversionValue: 2
          balance: gross
          includeNetProfitInterest: 'yes'
          workingInterest: 100
          netProfitInterest: 0
          netRevenueInterest: 100
          leaseNetRevenueInterest: 75
          oilNetRevenueInterest: null
          gasNetRevenueInterest: null
          nglNetRevenueInterest: null
          dripCondensateNetRevenueInterest: null
        secondReversion:
          reversionType: PayoutWithoutInvestment
          reversionValue: 4
          balance: gross
          includeNetProfitInterest: 'yes'
          workingInterest: 100
          netProfitInterest: 0
          netRevenueInterest: 100
          leaseNetRevenueInterest: 75
          oilNetRevenueInterest: 1
          gasNetRevenueInterest: null
          nglNetRevenueInterest: null
          dripCondensateNetRevenueInterest: null
        thirdReversion:
          reversionType: UndiscRoi
          reversionValue: 3
          balance: gross
          includeNetProfitInterest: 'yes'
          workingInterest: 100
          netProfitInterest: 0
          netRevenueInterest: 100
          leaseNetRevenueInterest: 75
          oilNetRevenueInterest: null
          gasNetRevenueInterest: null
          nglNetRevenueInterest: null
          dripCondensateNetRevenueInterest: null
        fourthReversion: null
        fifthReversion: null
        sixthReversion: null
        seventhReversion: null
        eighthReversion: null
        ninthReversion: null
        tenthReversion: null
    OwnershipReversionInput:
      type: object
      required:
      - name
      - unique
      properties:
        name:
          type: string
          description: Name
        unique:
          type: boolean
          description: Unique
        scenario:
          type: string
          description: Scenario ID
        well:
          type: string
          description: Well ID
        ownership:
          type: object
          properties:
            initialOwnership:
              type: object
              properties:
                workingInterest:
                  type: number
                  description: working Interest
                netProfitInterestType:
                  type: string
                  description: Net Profit Interest Type
                netProfitInterest:
                  type: number
                  description: Net Profit Interest
                netRevenueInterest:
                  type: number
                  description: Net Revenue Interest
                leaseNetRevenueInterest:
                  type: number
                  description: Lease Net Revenue Interest
                oilNetRevenueInterest:
                  type: number
                  description: Oil Net Revenue Interest
                gasNetRevenueInterest:
                  type: number
                  description: Gas Net Revenue Interest
                nglNetRevenueInterest:
                  type: number
                  description: Ngl Net Revenue Interest
                dripCondensateNetRevenueInterest:
                  type: number
                  description: Drip Condensate Net Revenue Interest
            firstReversion:
              $ref: '#/components/schemas/Reversion'
            secondReversion:
              $ref: '#/components/schemas/Reversion'
            thirdReversion:
              $ref: '#/components/schemas/Reversion'
            fourthReversion:
              $ref: '#/components/schemas/Reversion'
            fifthReversion:
              $ref: '#/components/schemas/Reversion'
            sixthReversion:
              $ref: '#/components/schemas/Reversion'
            seventhReversion:
              $ref: '#/components/schemas/Reversion'
            eighthReversion:
              $ref: '#/components/schemas/Reversion'
            ninthReversion:
              $ref: '#/components/schemas/Reversion'
            tenthReversion:
              $ref: '#/components/schemas/Reversion'
      example:
        name: Test
        scenario: 63b8571d70ed63f50bd6d63f
        unique: true
        well: 63b85759e1d7eb4e31579f51
        ownership:
          initialOwnership:
            workingInterest: 100
            netProfitInterestType: expense
            netProfitInterest: 0
            netRevenueInterest: 100
            leaseNetRevenueInterest: 75
            oilNetRevenueInterest: 4
            gasNetRevenueInterest: null
            nglNetRevenueInterest: null
            dripCondensateNetRevenueInterest: null
          firstReversion:
            reversionType: Irr
            reversionValue: 2
            balance: gross
            includeNetProfitInterest: 'yes'
            workingInterest: 100
            netProfitInterest: 0
            netRevenueInterest: 100
            leaseNetRevenueInterest: 75
            oilNetRevenueInterest: null
            gasNetRevenueInterest: null
            nglNetRevenueInterest: null
            dripCondensateNetRevenueInterest: null
          secondReversion:
            reversionType: PayoutWithoutInvestment
            reversionValue: 4
            balance: gross
            includeNetProfitInterest: 'yes'
            workingInterest: 100
            netProfitInterest: 0
            netRevenueInterest: 100
            leaseNetRevenueInterest: 75
            oilNetRevenueInterest: 1
            gasNetRevenueInterest: null
            nglNetRevenueInterest: null
            dripCondensateNetRevenueInterest: null
          thirdReversion:
            reversionType: UndiscRoi
            reversionValue: 3
            balance: gross
            includeNetProfitInterest: 'yes'
            workingInterest: 100
            netProfitInterest: 0
            netRevenueInterest: 100
            leaseNetRevenueInterest: 75
            oilNetRevenueInterest: null
            gasNetRevenueInterest: null
            nglNetRevenueInterest: null
            dripCondensateNetRevenueInterest: null
          fourthReversion: null
          fifthReversion: null
          sixthReversion: null
          seventhReversion: null
          eighthReversion: null
          ninthReversion: null
          tenthReversion: null
    OwnershipReversionInputList:
      type: array
      items:
        $ref: '#/components/schemas/OwnershipReversionInput'
      maxItems: 500
      example:
      - name: Test
        scenario: 63b8571d70ed63f50bd6d63f
        unique: true
        well: 63b85759e1d7eb4e31579f51
        ownership: null
        initialOwnership:
          workingInterest: 100
          netProfitInterestType: expense
          netProfitInterest: 0
          netRevenueInterest: 100
          leaseNetRevenueInterest: 75
          oilNetRevenueInterest: 4
          gasNetRevenueInterest: null
          nglNetRevenueInterest: null
          dripCondensateNetRevenueInterest: null
        firstReversion:
          reversionType: Irr
          reversionValue: 2
          balance: gross
          includeNetProfitInterest: 'yes'
          workingInterest: 100
          netProfitInterest: 0
          netRevenueInterest: 100
          leaseNetRevenueInterest: 75
          oilNetRevenueInterest: null
          gasNetRevenueInterest: null
          nglNetRevenueInterest: null
          dripCondensateNetRevenueInterest: null
        secondReversion:
          reversionType: PayoutWithoutInvestment
          reversionValue: 4
          balance: gross
          includeNetProfitInterest: 'yes'
          workingInterest: 100
          netProfitInterest: 0
          netRevenueInterest: 100
          leaseNetRevenueInterest: 75
          oilNetRevenueInterest: 1
          gasNetRevenueInterest: null
          nglNetRevenueInterest: null
          dripCondensateNetRevenueInterest: null
        thirdReversion:
          reversionType: UndiscRoi
          reversionValue: 3
          balance: gross
          includeNetProfitInterest: 'yes'
          workingInterest: 100
          netProfitInterest: 0
          netRevenueInterest: 100
          leaseNetRevenueInterest: 75
          oilNetRevenueInterest: null
          gasNetRevenueInterest: null
          nglNetRevenueInterest: null
          dripCondensateNetRevenueInterest: null
        fourthReversion: null
        fifthReversion: null
        sixthReversion: null
        seventhReversion: null
        eighthReversion: null
        ninthReversion: null
        tenthReversion: null
  parameters:
    takeParam:
      name: take
      in: query
      description: max records to return
      schema:
        type: integer
        format: int32
        default: 25
        maximum: 200
        minimum: 1
    skipParam:
      name: skip
      in: query
      description: number of items to skip
      schema:
        type: integer
        format: int32
        default: 0
    cursorParam:
      name: cursor
      in: query
      description: used in pagination to get the next page
      schema:
        type: string
    sortParam:
      name: sort
      in: query
      description: field to sort by, including + or - at the beginning for ascending or descending order, respectively
      schema:
        type: string
  securitySchemes:
    api-key:
      type: apiKey
      name: x-api-key
      in: header
x-google-management:
  metrics:
  - name: read-request-rate
    displayName: Read Request Rate
    valueType: INT64
    metricKind: DELTA
  - name: write-request-rate
    displayName: Write Request Rate
    valueType: INT64
    metricKind: DELTA
  quota:
    limits:
    - name: read-request-rate-limit
      metric: read-request-rate
      unit: 1/min/{project}
      values:
        STANDARD: 800
    - name: write-request-rate-limit
      metric: write-request-rate
      unit: 1/min/{project}
      values:
        STANDARD: 200
