openapi: 3.2.0
info:
  title: ComboCurve REST Project Monthly Productions API
  version: 1.0.0
servers:
- url: https://api.combocurve.com
security:
- api-key: []
  service-account-key: []
tags:
- name: ProjectMonthlyProductions
paths:
  /v1/projects/{projectId}/monthly-productions:
    delete:
      description: Delete the monthly productions documents that match the given filters.
      operationId: delete-project-monthly-productions
      parameters:
      - in: path
        name: projectId
        required: true
        description: ''
        schema:
          type: string
      - name: well
        in: query
        description: filter by well ID
        required: true
        schema:
          type: string
      - name: startDate
        in: query
        description: filter by startDate
        schema:
          type: string
      - name: endDate
        in: query
        description: filter by endDate
        schema:
          type: string
      responses:
        '204':
          description: OK
          headers:
            X-Delete-Count:
              description: The number of records that match the given filters and were deleted.
              schema:
                type: integer
        '400':
          description: Bad Request. There is something wrong with the request data.
      tags:
      - ProjectMonthlyProductions
      summary: Delete project monthly productions
      x-summary-source: derived
    head:
      description: Returns metadata about the existing monthly production documents in the specified project's scope.
      operationId: head-projects-monthly-productions
      parameters:
      - in: path
        name: projectId
        required: true
        description: ''
        schema:
          type: string
      - $ref: '#/components/parameters/skipParam'
      - $ref: '#/components/parameters/takeParam'
      - name: createdAt
        in: query
        description: filter by createdAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example createdAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      - name: well
        in: query
        description: filter by well
        x-allow-multiple: true
        schema:
          type: string
      - name: updatedAt
        in: query
        description: filter by updatedAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example updatedAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: OK
          headers:
            Link:
              description: Indicates a typed relationship with another resource, where the relation type is defined by RFC 5988. We include the relationships next, prev, first and last, which can be used to move between pages of the list of results.
              schema:
                type: string
            X-Query-Count:
              description: The number of records in this resource. When filters are provided only matching records are counted.
              schema:
                type: integer
        '400':
          description: Bad Request. There is something wrong with the request data.
      tags:
      - ProjectMonthlyProductions
      summary: Head projects monthly productions
      x-summary-source: derived
    get:
      description: Returns a list of monthly production documents in the specified project's scope.
      operationId: get-projects-monthly-productions
      parameters:
      - in: path
        name: projectId
        required: true
        description: ''
        schema:
          type: string
      - $ref: '#/components/parameters/skipParam'
      - $ref: '#/components/parameters/takeParam'
      - $ref: '#/components/parameters/sortParam'
      - $ref: '#/components/parameters/cursorParam'
      - name: createdAt
        in: query
        description: filter by createdAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example createdAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      - name: well
        in: query
        description: filter by well
        x-allow-multiple: true
        schema:
          type: string
      - name: updatedAt
        in: query
        description: filter by updatedAt - Operator values are [lt] = less than, [le] = less than or equal, [gt] = greater than, [ge] = greater than or equal, no operator = equal. Example updatedAt[gt]=2018-01-01T00:00:00Z
        x-allow-parameter-operator: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: OK
          headers:
            Link:
              description: Indicates a typed relationship with another resource, where the relation type is defined by RFC 5988. We include the relationships next, prev, first and last, which can be used to move between pages of the list of results.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonthlyProductionList'
              example:
              - choke: 13
                co2Injection: 123
                createdAt: '2020-01-21T16:58:08.986Z'
                date: '2017-01-15T00:00:00.000Z'
                customNumber0: 123
                customNumber1: 123
                customNumber2: 123
                customNumber3: 123
                customNumber4: 123
                customNumber5: 123
                customNumber6: 123
                customNumber7: 123
                customNumber8: 123
                customNumber9: 123
                customNumber10: 123
                customNumber11: 123
                customNumber12: 123
                customNumber13: 123
                customNumber14: 123
                customNumber15: 123
                customNumber16: 123
                customNumber17: 123
                customNumber18: 123
                customNumber19: 123
                daysOn: 30
                gas: 16925
                gasInjection: 123
                ngl: 123
                oil: 1022
                operationalTag: Start of production
                steamInjection: 123
                updatedAt: '2020-01-21T17:58:08.986Z'
                water: 4631
                waterInjection: 123
                well: 5e286e0d8f3df51d7ae744a3
              - choke: 13
                co2Injection: 123
                createdAt: '2020-01-21T16:58:08.986Z'
                date: '2017-01-15T00:00:00.000Z'
                customNumber0: 123
                customNumber1: 123
                customNumber2: 123
                customNumber3: 123
                customNumber4: 123
                customNumber5: 123
                customNumber6: 123
                customNumber7: 123
                customNumber8: 123
                customNumber9: 123
                customNumber10: 123
                customNumber11: 123
                customNumber12: 123
                customNumber13: 123
                customNumber14: 123
                customNumber15: 123
                customNumber16: 123
                customNumber17: 123
                customNumber18: 123
                customNumber19: 123
                daysOn: 30
                gas: 16925
                gasInjection: 123
                ngl: 123
                oil: 1022
                operationalTag: Start of production
                steamInjection: 123
                updatedAt: '2020-01-21T17:58:08.986Z'
                water: 4631
                waterInjection: 123
                well: 5e286e0d8f3df51d7ae744a3
        '400':
          description: Bad Request. There is something wrong with the request data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                name: ValidationError
                message: The field 'id' is required.
                details:
                  location: In body of request at position [0]
      tags:
      - ProjectMonthlyProductions
      x-google-quota:
        metricCosts:
          read-request-rate: 1
      summary: Get projects monthly productions
      x-summary-source: derived
    post:
      description: Upserts a list of monthly production documents in projectId scope.
      operationId: post-projects-monthly-productions
      parameters:
      - in: path
        name: projectId
        required: true
        description: ''
        schema:
          type: string
      responses:
        '207':
          description: Multi-Status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductionMultiStatusResponse'
              example:
                generalErrors:
                - name: ValidationError
                  message: The field 'well' is required.
                  location: In body of request at position [0]
                - name: ValidationError
                  message: The field 'date' is required.
                  location: In body of request at position [2]
                results:
                - status: Success
                  code: 200
                  well: 62b1c13e2750169012ee4515
                  date: '2023-01-01T00:00:00.000Z'
                - status: Success
                  code: 200
                  well: 62b1c13e4857169000ee4613
                  date: '2023-01-01T00:00:00.000Z'
                failedCount: 2
                successCount: 2
      tags:
      - ProjectMonthlyProductions
      x-google-quota:
        metricCosts:
          write-request-rate: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonthlyProductionInputList'
        description: Monthly production document(s) to insert. See MonthlyProductionInputList.
      summary: Post projects monthly productions
      x-summary-source: derived
    put:
      description: Upserts a list of monthly production documents in projectId scope.
      operationId: put-projects-monthly-productions
      parameters:
      - in: path
        name: projectId
        required: true
        description: ''
        schema:
          type: string
      responses:
        '207':
          description: Multi-Status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductionMultiStatusResponse'
              example:
                generalErrors:
                - name: ValidationError
                  message: The field 'well' is required.
                  location: In body of request at position [0]
                - name: ValidationError
                  message: The field 'date' is required.
                  location: In body of request at position [2]
                results:
                - status: Success
                  code: 200
                  well: 62b1c13e2750169012ee4515
                  date: '2023-01-01T00:00:00.000Z'
                - status: Success
                  code: 200
                  well: 62b1c13e4857169000ee4613
                  date: '2023-01-01T00:00:00.000Z'
                failedCount: 2
                successCount: 2
      tags:
      - ProjectMonthlyProductions
      x-google-quota:
        metricCosts:
          write-request-rate: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonthlyProductionInputList'
        description: Monthly production document(s) to upsert. See MonthlyProductionInputList.
      summary: Put projects monthly productions
      x-summary-source: derived
    patch:
      description: Patch a list of monthly production documents in projectId scope.
      operationId: patch-projects-monthly-productions
      parameters:
      - in: path
        name: projectId
        required: true
        description: ''
        schema:
          type: string
      responses:
        '207':
          description: Multi-Status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductionMultiStatusResponse'
              example:
                generalErrors:
                - name: ValidationError
                  message: The field 'well' is required.
                  location: In body of request at position [0]
                - name: ValidationError
                  message: The field 'date' is required.
                  location: In body of request at position [2]
                results:
                - status: Success
                  code: 200
                  well: 62b1c13e2750169012ee4515
                  date: '2023-01-01T00:00:00.000Z'
                - status: Success
                  code: 200
                  well: 62b1c13e4857169000ee4613
                  date: '2023-01-01T00:00:00.000Z'
                failedCount: 2
                successCount: 2
      tags:
      - ProjectMonthlyProductions
      x-google-quota:
        metricCosts:
          write-request-rate: 1
      x-is-patch: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonthlyProductionPatchInputList'
        description: Monthly production document(s) to patch. See MonthlyProductionPatchInputList.
      summary: Patch projects monthly productions
      x-summary-source: derived
components:
  schemas:
    Error:
      type: object
      properties:
        name:
          type: string
          description: The kind of error.
        message:
          type: string
          description: A human-readable description of the problem.
        details:
          type: object
          properties:
            location:
              type: string
              description: The location in the request data that contains the invalid value.
      example:
        name: ValidationError
        message: The field 'id' is required.
        details:
          location: In body of request at position [0]
    MonthlyProductionList:
      type: array
      items:
        $ref: '#/components/schemas/MonthlyProduction'
      maxItems: 20000
      example:
      - choke: 13
        co2Injection: 123
        createdAt: '2020-01-21T16:58:08.986Z'
        date: '2017-01-15T00:00:00.000Z'
        customNumber0: 123
        customNumber1: 123
        customNumber2: 123
        customNumber3: 123
        customNumber4: 123
        customNumber5: 123
        customNumber6: 123
        customNumber7: 123
        customNumber8: 123
        customNumber9: 123
        customNumber10: 123
        customNumber11: 123
        customNumber12: 123
        customNumber13: 123
        customNumber14: 123
        customNumber15: 123
        customNumber16: 123
        customNumber17: 123
        customNumber18: 123
        customNumber19: 123
        daysOn: 30
        gas: 16925
        gasInjection: 123
        ngl: 123
        oil: 1022
        operationalTag: Start of production
        steamInjection: 123
        updatedAt: '2020-01-21T17:58:08.986Z'
        water: 4631
        waterInjection: 123
        well: 5e286e0d8f3df51d7ae744a3
      - choke: 13
        co2Injection: 123
        createdAt: '2020-01-21T16:58:08.986Z'
        date: '2017-01-15T00:00:00.000Z'
        customNumber0: 123
        customNumber1: 123
        customNumber2: 123
        customNumber3: 123
        customNumber4: 123
        customNumber5: 123
        customNumber6: 123
        customNumber7: 123
        customNumber8: 123
        customNumber9: 123
        customNumber10: 123
        customNumber11: 123
        customNumber12: 123
        customNumber13: 123
        customNumber14: 123
        customNumber15: 123
        customNumber16: 123
        customNumber17: 123
        customNumber18: 123
        customNumber19: 123
        daysOn: 30
        gas: 16925
        gasInjection: 123
        ngl: 123
        oil: 1022
        operationalTag: Start of production
        steamInjection: 123
        updatedAt: '2020-01-21T17:58:08.986Z'
        water: 4631
        waterInjection: 123
        well: 5e286e0d8f3df51d7ae744a3
    ProductionStatus:
      type: object
      required:
      - status
      - code
      properties:
        status:
          type: string
        code:
          type: integer
        well:
          type: string
        date:
          type: string
          format: date
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorEntry'
      example:
        status: Success
        code: 200
        well: 62b1c13e2750169012ee4515
        date: '2023-01-01T00:00:00.000Z'
    MonthlyProductionInput:
      type: object
      required:
      - date
      properties:
        date:
          type: string
          format: date
          description: Date
        choke:
          type: number
          description: Choke (in)
        chosenID:
          type: string
          maxLength: 16384
          description: Chosen ID
        co2Injection:
          type: number
        customNumber0:
          type: number
        customNumber1:
          type: number
        customNumber2:
          type: number
        customNumber3:
          type: number
        customNumber4:
          type: number
        customNumber5:
          type: number
        customNumber6:
          type: number
        customNumber7:
          type: number
        customNumber8:
          type: number
        customNumber9:
          type: number
        customNumber10:
          type: number
        customNumber11:
          type: number
        customNumber12:
          type: number
        customNumber13:
          type: number
        customNumber14:
          type: number
        customNumber15:
          type: number
        customNumber16:
          type: number
        customNumber17:
          type: number
        customNumber18:
          type: number
        customNumber19:
          type: number
        dataSource:
          type: string
          description: Data Source
        daysOn:
          type: number
          description: Days On
        gas:
          type: number
          description: Gas (MCF/MO)
        gasInjection:
          type: number
        ngl:
          type: number
        oil:
          type: number
          description: Oil (BBL/MO)
        operationalTag:
          type: string
          maxLength: 16384
          description: Operational Tag
        steamInjection:
          type: number
        water:
          type: number
          description: Water (BBL/MO)
        waterInjection:
          type: number
        well:
          type: string
          description: Well
      example:
        choke: 13
        chosenID: 28058901650448
        co2Injection: 123
        customNumber0: 123
        customNumber1: 123
        customNumber2: 123
        customNumber3: 123
        customNumber4: 123
        customNumber5: 123
        customNumber6: 123
        customNumber7: 123
        customNumber8: 123
        customNumber9: 123
        customNumber10: 123
        customNumber11: 123
        customNumber12: 123
        customNumber13: 123
        customNumber14: 123
        customNumber15: 123
        customNumber16: 123
        customNumber17: 123
        customNumber18: 123
        customNumber19: 123
        dataSource: internal
        date: '2017-01-15T00:00:00.000Z'
        daysOn: 30
        gas: 16925
        gasInjection: 123
        ngl: 123
        oil: 1022
        operationalTag: Start of production
        steamInjection: 123
        water: 4631
        waterInjection: 123
        well: 5e286e0d8f3df51d7ae744a3
    MonthlyProductionPatchInputList:
      type: array
      x-is-patch: true
      items:
        $ref: '#/components/schemas/MonthlyProductionPatchInput'
      maxItems: 20000
      example:
      - choke: 13
        chosenID: 28058901650448
        co2Injection: 123
        customNumber0: 123
        customNumber1: 123
        customNumber2: 123
        customNumber3: 123
        customNumber4: 123
        customNumber5: 123
        customNumber6: 123
        customNumber7: 123
        customNumber8: 123
        customNumber9: 123
        customNumber10: 123
        customNumber11: 123
        customNumber12: 123
        customNumber13: 123
        customNumber14: 123
        customNumber15: 123
        customNumber16: 123
        customNumber17: 123
        customNumber18: 123
        customNumber19: 123
        dataSource: internal
        date: '2017-01-15T00:00:00.000Z'
        daysOn: 30
        gas: 16925
        gasInjection: 123
        ngl: 123
        oil: 1022
        operationalTag: Start of production
        steamInjection: 123
        water: 4631
        waterInjection: 123
        well: 5e286e0d8f3df51d7ae744a3
      - choke: 13
        chosenID: 28058901650555
        co2Injection: 123
        customNumber0: 123
        customNumber1: 123
        customNumber2: 123
        customNumber3: 123
        customNumber4: 123
        customNumber5: 123
        customNumber6: 123
        customNumber7: 123
        customNumber8: 123
        customNumber9: 123
        customNumber10: 123
        customNumber11: 123
        customNumber12: 123
        customNumber13: 123
        customNumber14: 123
        customNumber15: 123
        customNumber16: 123
        customNumber17: 123
        customNumber18: 123
        customNumber19: 123
        dataSource: internal
        date: '2020-02-15T00:00:00.000Z'
        daysOn: 30
        gas: 16925
        gasInjection: 123
        ngl: 123
        oil: 1022
        operationalTag: Start of production
        steamInjection: 123
        water: 4631
        waterInjection: 123
        well: 5e281e0d8f3df51d7ae845j3
    ErrorEntry:
      required:
      - name
      - message
      type: object
      properties:
        name:
          type: string
        message:
          type: string
        location:
          type: string
      example:
        name: ValidationError
        message: The field 'id' is required.
        location: In body of request at position [0]
    MonthlyProductionPatchInput:
      type: object
      x-is-patch: true
      required:
      - date
      properties:
        date:
          type: string
          format: date
          description: Date
        choke:
          type: number
          description: Choke (in)
        chosenID:
          type: string
          maxLength: 16384
          description: Chosen ID
        co2Injection:
          type: number
        customNumber0:
          type: number
        customNumber1:
          type: number
        customNumber2:
          type: number
        customNumber3:
          type: number
        customNumber4:
          type: number
        customNumber5:
          type: number
        customNumber6:
          type: number
        customNumber7:
          type: number
        customNumber8:
          type: number
        customNumber9:
          type: number
        customNumber10:
          type: number
        customNumber11:
          type: number
        customNumber12:
          type: number
        customNumber13:
          type: number
        customNumber14:
          type: number
        customNumber15:
          type: number
        customNumber16:
          type: number
        customNumber17:
          type: number
        customNumber18:
          type: number
        customNumber19:
          type: number
        dataSource:
          type: string
          description: Data Source
        daysOn:
          type: number
          description: Days On
        gas:
          type: number
          description: Gas (MCF/MO)
        gasInjection:
          type: number
        ngl:
          type: number
        oil:
          type: number
          description: Oil (BBL/MO)
        operationalTag:
          type: string
          maxLength: 16384
          description: Operational Tag
        steamInjection:
          type: number
        water:
          type: number
          description: Water (BBL/MO)
        waterInjection:
          type: number
        well:
          type: string
          description: Well
      example:
        choke: 13
        chosenID: 28058901650448
        co2Injection: 123
        customNumber0: 123
        customNumber1: 123
        customNumber2: 123
        customNumber3: 123
        customNumber4: 123
        customNumber5: 123
        customNumber6: 123
        customNumber7: 123
        customNumber8: 123
        customNumber9: 123
        customNumber10: 123
        customNumber11: 123
        customNumber12: 123
        customNumber13: 123
        customNumber14: 123
        customNumber15: 123
        customNumber16: 123
        customNumber17: 123
        customNumber18: 123
        customNumber19: 123
        dataSource: internal
        date: '2017-01-15T00:00:00.000Z'
        daysOn: 30
        gas: 16925
        gasInjection: 123
        ngl: 123
        oil: 1022
        operationalTag: Start of production
        steamInjection: 123
        water: 4631
        waterInjection: 123
        well: 5e286e0d8f3df51d7ae744a3
    MonthlyProductionInputList:
      type: array
      items:
        $ref: '#/components/schemas/MonthlyProductionInput'
      maxItems: 20000
      example:
      - choke: 13
        chosenID: 28058901650448
        co2Injection: 123
        customNumber0: 123
        customNumber1: 123
        customNumber2: 123
        customNumber3: 123
        customNumber4: 123
        customNumber5: 123
        customNumber6: 123
        customNumber7: 123
        customNumber8: 123
        customNumber9: 123
        customNumber10: 123
        customNumber11: 123
        customNumber12: 123
        customNumber13: 123
        customNumber14: 123
        customNumber15: 123
        customNumber16: 123
        customNumber17: 123
        customNumber18: 123
        customNumber19: 123
        dataSource: internal
        date: '2017-01-15T00:00:00.000Z'
        daysOn: 30
        gas: 16925
        gasInjection: 123
        ngl: 123
        oil: 1022
        operationalTag: Start of production
        steamInjection: 123
        water: 4631
        waterInjection: 123
        well: 5e286e0d8f3df51d7ae744a3
      - choke: 13
        chosenID: 28058901650555
        co2Injection: 123
        customNumber0: 123
        customNumber1: 123
        customNumber2: 123
        customNumber3: 123
        customNumber4: 123
        customNumber5: 123
        customNumber6: 123
        customNumber7: 123
        customNumber8: 123
        customNumber9: 123
        customNumber10: 123
        customNumber11: 123
        customNumber12: 123
        customNumber13: 123
        customNumber14: 123
        customNumber15: 123
        customNumber16: 123
        customNumber17: 123
        customNumber18: 123
        customNumber19: 123
        dataSource: internal
        date: '2020-02-15T00:00:00.000Z'
        daysOn: 30
        gas: 16925
        gasInjection: 123
        ngl: 123
        oil: 1022
        operationalTag: Start of production
        steamInjection: 123
        water: 4631
        waterInjection: 123
        well: 5e281e0d8f3df51d7ae845j3
    ProductionMultiStatusResponse:
      type: object
      properties:
        generalErrors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorEntry'
        results:
          type: array
          items:
            $ref: '#/components/schemas/ProductionStatus'
        failedCount:
          type: integer
        successCount:
          type: integer
      example:
        generalErrors:
        - name: ValidationError
          message: The field 'well' is required.
          location: In body of request at position [0]
        - name: ValidationError
          message: The field 'date' is required.
          location: In body of request at position [2]
        results:
        - status: Success
          code: 200
          well: 62b1c13e2750169012ee4515
          date: '2023-01-01T00:00:00.000Z'
        - status: Success
          code: 200
          well: 62b1c13e4857169000ee4613
          date: '2023-01-01T00:00:00.000Z'
        failedCount: 2
        successCount: 2
    MonthlyProduction:
      type: object
      required:
      - date
      properties:
        date:
          type: string
          format: date
          description: Date
        choke:
          type: number
          description: Choke (in)
        co2Injection:
          type: number
        createdAt:
          type: string
          format: date
          description: Project Creation Date
        customNumber0:
          type: number
        customNumber1:
          type: number
        customNumber2:
          type: number
        customNumber3:
          type: number
        customNumber4:
          type: number
        customNumber5:
          type: number
        customNumber6:
          type: number
        customNumber7:
          type: number
        customNumber8:
          type: number
        customNumber9:
          type: number
        customNumber10:
          type: number
        customNumber11:
          type: number
        customNumber12:
          type: number
        customNumber13:
          type: number
        customNumber14:
          type: number
        customNumber15:
          type: number
        customNumber16:
          type: number
        customNumber17:
          type: number
        customNumber18:
          type: number
        customNumber19:
          type: number
        daysOn:
          type: number
          description: Days On
        gas:
          type: number
          description: Gas (MCF/MO)
        gasInjection:
          type: number
        ngl:
          type: number
        oil:
          type: number
          description: Oil (BBL/MO)
        operationalTag:
          type: string
          maxLength: 16384
          description: Operational Tag
        steamInjection:
          type: number
        updatedAt:
          type: string
          format: date
          description: Updated At
        water:
          type: number
          description: Water (BBL/MO)
        waterInjection:
          type: number
        well:
          type: string
          description: Well
      example:
        choke: 13
        co2Injection: 123
        date: '2017-01-15T00:00:00.000Z'
        createdAt: '2020-01-21T16:58:08.986Z'
        customNumber0: 123
        customNumber1: 123
        customNumber2: 123
        customNumber3: 123
        customNumber4: 123
        customNumber5: 123
        customNumber6: 123
        customNumber7: 123
        customNumber8: 123
        customNumber9: 123
        customNumber10: 123
        customNumber11: 123
        customNumber12: 123
        customNumber13: 123
        customNumber14: 123
        customNumber15: 123
        customNumber16: 123
        customNumber17: 123
        customNumber18: 123
        customNumber19: 123
        daysOn: 30
        gas: 16925
        gasInjection: 123
        ngl: 123
        oil: 1022
        operationalTag: Start of production
        steamInjection: 123
        updatedAt: '2020-01-21T17:58:08.986Z'
        water: 4631
        waterInjection: 123
        well: 5e286e0d8f3df51d7ae744a3
  parameters:
    takeParam:
      name: take
      in: query
      description: max records to return
      schema:
        type: integer
        format: int32
        default: 25
        maximum: 200
        minimum: 1
    skipParam:
      name: skip
      in: query
      description: number of items to skip
      schema:
        type: integer
        format: int32
        default: 0
    cursorParam:
      name: cursor
      in: query
      description: used in pagination to get the next page
      schema:
        type: string
    sortParam:
      name: sort
      in: query
      description: field to sort by, including + or - at the beginning for ascending or descending order, respectively
      schema:
        type: string
  securitySchemes:
    api-key:
      type: apiKey
      name: x-api-key
      in: header
x-google-management:
  metrics:
  - name: read-request-rate
    displayName: Read Request Rate
    valueType: INT64
    metricKind: DELTA
  - name: write-request-rate
    displayName: Write Request Rate
    valueType: INT64
    metricKind: DELTA
  quota:
    limits:
    - name: read-request-rate-limit
      metric: read-request-rate
      unit: 1/min/{project}
      values:
        STANDARD: 800
    - name: write-request-rate-limit
      metric: write-request-rate
      unit: 1/min/{project}
      values:
        STANDARD: 200
x-provenance:
  method: harvested
  publisher: ComboCurve
  source: https://storage.googleapis.com/beta-combocurve-api-docs/openapi-spec.yaml
  note: split by refine-openapis from the provider's own published document, verified by fetch (openapi/_original/*.fetch.json);
    stamped by stamp-openapi-provenance.py (roadmap#793)
